# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'calendar' do
  use_frameworks!
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Firebase/Database'
  pod 'CodableFirebase'
  
end
